# Generated by Django 6.0.1 on 2026-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Tasdıqlaw kodı')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Jaratılǵan waqtı')),
                ('is_used', models.BooleanField(default=False, verbose_name='Paydalanıldı')),
            ],
            options={
                'verbose_name': 'Telegram Autentifikaciya',
                'verbose_name_plural': 'Telegram Autentifikaciyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
