# Generated by Django 6.0.1 on 2026-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_telegramauthsession_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauthsession',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nomeri'),
        ),
    ]
