# Generated by Django 6.0.1 on 2026-01-15 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sebet',
                'verbose_name_plural': 'Sebetler',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Sebetdegi onim',
                'verbose_name_plural': 'Sebet onimler',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya ati')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ulıwma bahasi')),
                ('status', models.CharField(choices=[('pending', 'kutilip atir'), ('paid', 'tolendi'), ('shipped', 'jiberildi'), ('cancelled', 'biykar qilindi')], default='pending', max_length=20, verbose_name='Jaǵdayı')),
                ('address', models.TextField(verbose_name='Jetkerip beriw mánzili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Buyırtpa qiling'an waqtı")),
            ],
            options={
                'verbose_name': 'Buyırtpa',
                'verbose_name_plural': 'Buyırtpalar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Sani')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bahasi')),
            ],
            options={
                'verbose_name': 'Buyırtpa dagi onim',
                'verbose_name_plural': 'Buyırtpa onimleri',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Onim ati')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Toliq maglıwmat')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bahası')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shegirmeli bahasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ónim súwreti')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Qoymadaǵı sanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satılıwda bar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Jaratılǵan waqtı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ózgertilgen waqtı')),
            ],
            options={
                'verbose_name': 'Ónim',
                'verbose_name_plural': 'Ónimler',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reyting')),
                ('comment', models.TextField(verbose_name='Kommentariya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Jazilg'an waqtı")),
            ],
            options={
                'verbose_name': 'Pikir',
                'verbose_name_plural': 'Pikirler',
            },
        ),
    ]
